runtime: nodejs16

env_variables:
  DATABASE_URL: 'mysql://gnjn8e7fwau0:pscale_pw_Kl8cECZyRqRsgP2mFdwGAjV05MKYaHFqFvruRaIoYvU@ey5d2chfadbl.us-east-1.psdb.cloud/deploy-test?sslaccept=strict'
  AUTH0_JWK_URI: "https://northeastern-teamz.us.auth0.com/.well-known/jwks.json"
  AUTH0_AUDIENCE: "https://api.emptystack"
  AUTH0_ISSUER: "https://northeastern-teamz.us.auth0.com/"
  PORT: 8080